"""Re-create all tables after full reset

Revision ID: 02b918ad9feb
Revises: 
Create Date: 2025-07-14 23:09:00.190583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b918ad9feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=True),
    sa.Column('syllable_count', sa.Integer(), nullable=False),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.Column('pariyat_url', sa.String(length=500), nullable=True),
    sa.Column('is_mixed_chanda', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('poetic_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('prosody', sa.String(length=50), nullable=False),
    sa.Column('meaning', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poetic_word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poetic_word_prosody'), ['prosody'], unique=False)
        batch_op.create_index(batch_op.f('ix_poetic_word_word'), ['word'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('upajati_sub_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sequence_pattern', sa.String(length=4), nullable=False),
    sa.Column('chanda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chanda_id'], ['chanda.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_pattern')
    )
    op.create_table('verse_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('layout_type', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_details', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('chanda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chanda_id'], ['chanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verse_example', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verse_example_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse_example', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verse_example_source_type'))

    op.drop_table('verse_example')
    op.drop_table('upajati_sub_type')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('poetic_word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poetic_word_word'))
        batch_op.drop_index(batch_op.f('ix_poetic_word_prosody'))

    op.drop_table('poetic_word')
    op.drop_table('chanda')
    # ### end Alembic commands ###
