"""Initial migration for Pali Chanda Center

Revision ID: 0d4c0b33fd30
Revises: 
Create Date: 2025-07-12 17:29:28.559876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4c0b33fd30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chanda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pattern', sa.String(length=200), nullable=False),
    sa.Column('syllable_count', sa.Integer(), nullable=False),
    sa.Column('description_short', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('poetic_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('prosody', sa.String(length=50), nullable=False),
    sa.Column('meaning', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poetic_word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poetic_word_prosody'), ['prosody'], unique=False)
        batch_op.create_index(batch_op.f('ix_poetic_word_word'), ['word'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('verse_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('verse_line1', sa.String(length=500), nullable=True),
    sa.Column('verse_line2', sa.String(length=500), nullable=True),
    sa.Column('verse_line3', sa.String(length=500), nullable=True),
    sa.Column('verse_line4', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_details', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('chanda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chanda_id'], ['chanda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verse_example', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verse_example_source_type'), ['source_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verse_example', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verse_example_source_type'))

    op.drop_table('verse_example')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('poetic_word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poetic_word_word'))
        batch_op.drop_index(batch_op.f('ix_poetic_word_prosody'))

    op.drop_table('poetic_word')
    op.drop_table('chanda')
    # ### end Alembic commands ###
