"""Fix circular imports and finalize structure

Revision ID: 370669bf9338
Revises: 6d41fd842b45
Create Date: 2025-07-12 19:37:15.775093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370669bf9338'
down_revision = '6d41fd842b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
