"""Add layout_type to VerseExample

Revision ID: 454fc21e14f3
Revises: 589814f2813d
Create Date: 2025-07-12 20:50:56.196810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454fc21e14f3'
down_revision = '589814f2813d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_example', sa.Column('layout_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verse_example', 'layout_type')
    # ### end Alembic commands ###
