"""Add pariyat_url to Chanda model

Revision ID: 589814f2813d
Revises: dff3d9dc78f0
Create Date: 2025-07-12 19:54:50.581506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589814f2813d'
down_revision = 'dff3d9dc78f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chanda', sa.Column('pariyat_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chanda', 'pariyat_url')
    # ### end Alembic commands ###
