"""Refactor VerseExample to support multiple stanzas

Revision ID: 5bb3334871e3
Revises: 454fc21e14f3
Create Date: 2025-07-12 21:42:28.962315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb3334871e3'
down_revision = '454fc21e14f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_example', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('verse_example', 'verse_line2')
    op.drop_column('verse_example', 'verse_line1')
    op.drop_column('verse_example', 'verse_line4')
    op.drop_column('verse_example', 'verse_line3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_example', sa.Column('verse_line3', sa.VARCHAR(length=500), nullable=True))
    op.add_column('verse_example', sa.Column('verse_line4', sa.VARCHAR(length=500), nullable=True))
    op.add_column('verse_example', sa.Column('verse_line1', sa.VARCHAR(length=500), nullable=True))
    op.add_column('verse_example', sa.Column('verse_line2', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('verse_example', 'content')
    # ### end Alembic commands ###
