"""Restructure project with blueprints

Revision ID: 6d41fd842b45
Revises: 0d4c0b33fd30
Create Date: 2025-07-12 17:55:31.486870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d41fd842b45'
down_revision = '0d4c0b33fd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
