"""Add translation field to VerseExample

Revision ID: 88cda5167679
Revises: 5bb3334871e3
Create Date: 2025-07-14 00:08:51.640904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cda5167679'
down_revision = '5bb3334871e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse_example', sa.Column('translation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verse_example', 'translation')
    # ### end Alembic commands ###
