"""Fix circular imports and finalize structure

Revision ID: dff3d9dc78f0
Revises: 370669bf9338
Create Date: 2025-07-12 19:39:19.486774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff3d9dc78f0'
down_revision = '370669bf9338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
